

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 15.0

[window]
decorations = "buttonless"
padding = { x = 10, y = 10 }
startup_mode = "Maximized"
option_as_alt = "Both"

[general]
import = ["./themes/rose-pine.toml"]
